Display:MSM8916 : Missing header Files Fix:Build errors
hardware/qcom/display-caf/msm8916/libcopybit/software_converter.cpp:61:5:
error: use of undeclared identifier 'memcpy'
    memcpy((char *)yv12_handle->base,(char
*)hnd->base,y_size);
    ^
hardware/qcom/display-caf/msm8916/libcopybit/software_converter.cpp:155:9:
error: use of undeclared identifier 'memcpy'
        memcpy(dst, src, width);
        ^
hardware/qcom/display-caf/msm8916/libcopybit/software_converter.cpp:166:9:
error: use of undeclared identifier 'memcpy'
        memcpy(dst, src, info.src_stride);